twig:
    form_themes:
        - '@EzPlatformDrawIOFieldType/adminui/field/ezdrawio_edit.html.twig'

ezpublish:
    system:
        default:
            field_templates:
                - { template: '@EzPlatformDrawIOFieldType/ezdrawio_view.html.twig', priority: 0 }
        admin_group:
            field_templates:
                - { template: '@EzPlatformDrawIOFieldType/adminui/field/ezdrawio_view.html.twig', priority: 10 }
            fielddefinition_settings_templates:
                - { template: '@EzPlatformDrawIOFieldType/adminui/field/ezdrawio_settings.html.twig', priority: 10 }
