services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Type:
        public: true
        arguments:
            $validators: ['@ezpublish.fieldType.validator.black_list', '@ezpublish.fieldType.validator.image']
        tags:
            - { name: ezplatform.field_type, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Converter:
        public: true
        arguments:
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.core.io.image_fieldtype.legacy_url_redecorator"
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Storage:
        public: true
        arguments:
            - "@ezpublish.fieldType.ezimage.storage_gateway"
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.fieldType.ezimage.pathGenerator"
            - "@ezpublish.fieldType.metadataHandler.imagesize"
            - "@ezpublish.utils.deprecation_warner"
            - "@?ezpublish.image_alias.imagine.alias_cleaner"
        tags:
            - { name: ezplatform.field_type.external_storage_handler, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\SearchField:
        public: true
        tags:
            - { name: ezplatform.field_type.indexable, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Form\FormMapper:
        public: true
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: ezdrawio }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Form\FormType:
        public: true
        arguments:
            $ioService: "@ezpublish.fieldType.ezimage.io_service"
        tags:
            - { name: form.type }
