services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Type:
        public: true
        tags:
            - { name: ezpublish.fieldType, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Converter:
        public: true
        arguments:
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.core.io.image_fieldtype.legacy_url_redecorator"
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Storage:
        public: true
        arguments:
            - "@ezpublish.fieldType.ezimage.storage_gateway"
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.fieldType.ezimage.pathGenerator"
            - "@ezpublish.fieldType.metadataHandler.imagesize"
            - "@ezpublish.utils.deprecation_warner"
            - "@?ezpublish.image_alias.imagine.alias_cleaner"
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\SearchField:
        public: true
        tags:
            - { name: ezpublish.fieldType.indexable, alias: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Form\FormMapper:
        public: true
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezdrawio }
            - { name: ez.fieldFormMapper.value, fieldType: ezdrawio }

    EzSystems\EzPlatformDrawIOFieldType\FieldType\DrawIO\Form\FormType:
        public: true
        arguments:
            $ioService: "@ezpublish.fieldType.ezimage.io_service"
        tags:
            - { name: form.type }

    ezdrawio.components.styles:
        class: EzSystems\EzPlatformAdminUi\Component\LinkComponent
        arguments:
            $href: '/bundles/ezplatformdrawiofieldtype/css/style.css'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    ezdrawio.components.edit_js:
        class: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        arguments:
            $template: 'EzPlatformDrawIOFieldTypeBundle:adminui/component:ezdrawio_edit_js.html.twig'
            $parameters: []
        tags:
            - { name: ezplatform.admin_ui.component, group: 'content-edit-form-after' }
            - { name: ezplatform.admin_ui.component, group: 'content-create-form-after' }
